script:
  - sudo pip install s3cmd

deploy:
  # Staging environment
  - provider: script
    script: s3cmd sync --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://preview.healthystartchildcare.com/
    on:
      branch: release-staging

  # Production environment
  - provider: script
    script: "s3cmd sync --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://healthystartchildcare.com/ && curl \"https://api.keycdn.com/zones/purge/49630.json\" -u $KEYCDN_APIKEY:"
    on:
      branch: master
      
notifications:
    email:
        on_failure: always