script:
  - sudo pip install s3cmd

deploy:
  # Staging environment
  - provider: script
    script: s3cmd sync --delete-removed --exclude '.git/*' -P -M -r ./ s3://preview.healthystartchildcare.com/


notifications:
    email:
        on_failure: always