name: Deploy to Staging

on:
  push:
    branches:
      - release-staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install s3cmd
        run: sudo pip install s3cmd

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/release-staging'
        run: s3cmd sync --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} --delete-removed --exclude '.git/*' --acl-public --preserve --no-mime-magic --guess-mime-type --recursive ./ s3://preview.healthystartchildcare.com/
